---
- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root

  tasks:
    - name: Creating groups
      group:
        name: admin
        state: present

    - name: Creating users
      user:
        name: "{{item.name}}"
        shell: /bin/bash
        password: $6$rounds=656000$iO7Q9L6/w8dUUQVf$rmtnxrQ15TGAfG5ODxQ/WGyEpTwk.vD1W.UtedmOlo9YNkrIwapYMjmKmteEnUJmRYucgUVxXUQy7gtenpLmw0
        update_password: on_create
        groups: "{{item.groups}}"
      with_items:
        - { name: admin, groups: "wheel, admin"}

    - name: Adding account to sudoers
      lineinfile: 
        path: /etc/sudoers.d/admin
        line: 'admin ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes 
        validate: 'visudo -cf %s'

    - name: setting up hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{item.hosts}}"
        insertafter: EOF
      with_items:
        - { hosts: "10.0.0.10 master"}
        - { hosts: "10.0.0.11 minion01"}
        - { hosts: "10.0.0.12 minion02"}

    - name: Setting up .ssh directory 
      file: 
        path: /home/admin/.ssh
        state: directory
        owner: admin
        group: admin
        mode: 0700

    - name: Setting up admin keys 
      copy: 
        src: ../files/admin/ssh_keys/
        dest: /home/admin/.ssh
        owner: admin
        group: admin
        mode: 0700

    - name: Set authorized keys
      authorized_key: 
        user: admin
        state: present 
        key: "{{ lookup('file', '../files/admin/ssh_keys/admin.pub') }}"

    - name: Set authorized keys
      authorized_key: 
        user: vagrant
        state: present 
        key: "{{ lookup('file', '../files/juan_munoz.pub') }}"
    
    - name: Configure SSH 
      copy:
        src: ..//files/etc/sshd_config
        dest: /etc/ssh/
        owner: root
        mode: 0600
        force: yes 

    - name: Restart service sshd, in all cases
      service:
        name: sshd
        state: restarted

    - name: Setting up bashrc
      copy:
        src: ../files/admin/.bashrc
        dest: /home/admin/
        owner: admin
        group: admin
        mode: 0700

    - name: ensure a list of packages installed
      tags: yum
      yum:
        name: "{{ yum_packages }}"
      vars:
        yum_packages:
        - git
        - wget
        - nc
        - bind-utils
        - net-tools
        - traceroute
        - rsync
        - vim
          
    - name: setting up ansible hosts file
      copy:
        src: ../files/etc/ansible/hosts
        dest: /etc/ansible/
        owner: root
        group: root
        mode: 0644
 
    - name: setting up ansible config file 
      copy:
        src: ../files/etc/ansible/ansible.cfg
        dest: /etc/ansible/
        owner: root
        group: root 
        mode: 0644
        backup: yes
