# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  os = "centos/7"

  config.vm.define :controller, primary: true do |controller_config|
    controller_config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.name = "controller"
    end

    controller_config.vm.box = "#{os}"
    controller_config.vm.host_name = 'controller'
    controller_config.vm.network "private_network", ip: "192.168.1.10"
  end
 
  [
    ["node01",    "192.168.1.11",    "1024",    os ],
    ["node02",    "192.168.1.12",    "1024",    os ],
  ].each do |vmname,ip,mem,os|
    config.vm.define "#{vmname}" do |minion_config|
      minion_config.vm.provider "virtualbox" do |vb|
          vb.memory = "#{mem}"
          vb.cpus = 1
          vb.name = "#{vmname}"
      end

      minion_config.vm.box = "#{os}"
      minion_config.vm.hostname = "#{vmname}"
      minion_config.vm.network "private_network", ip: "#{ip}"
    end
  end
   config.vm.provision "ansible" do |ansible|
     ansible.playbook = "provisioning/main.yml"
   end
end
